name: Continuous Integration/Continuous Deployment
on: 
  push:
    branches:
      - workflow_CI-CD
  #    - main 
  #workflow_run:
  #  workflows: ["Continuous Training"]
  #  branches: [main]
  #  types:
  #    - completed
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CI/CD
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    env:
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Set environment and bring the model
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      
      - name: Cargando el modelo
        run: | 
          pip install dvc[gdrive]
          pip install --upgrade pyopenssl
          dvc pull model/model.pkl.dvc -r traker
      
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/prueba-ci-cd:latest
      
      #- name: Install and configure the Koyeb CLI
      #  uses: koyeb-community/install-koyeb-cli@v2
      #  with:
      #    api_token: "${{ secrets.KOYEB_TOKEN }}"
      #    github_token: "${{ secrets.GITHUB_TOKEN }}"
      
      #- name: Deploy to Koyeb
      #  run: koyeb service redeploy prueba-ci-cd/prueba-ci-cd

     