name: Testing API
on: 
  push:
    branches:
      - workflow_testing_api
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install dvc[gdrive]
          pip install -r requirements_test.txt
          pip install --upgrade pyopenssl
      - name: Lista de dependencias
        run: |
          pip list
      - name: Test API
        run: |
          dvc pull model/model.pkl -r traker
          pytest test.py